# permissions for end users to view postgreswriters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgreswriter-viewer-role
rules:
- apiGroups:
  - db.godx.com
  resources:
  - postgreswriters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.godx.com
  resources:
  - postgreswriters/status
  verbs:
  - get
