# permissions for end users to edit postgreswriters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgreswriter-editor-role
rules:
- apiGroups:
  - db.godx.com
  resources:
  - postgreswriters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.godx.com
  resources:
  - postgreswriters/status
  verbs:
  - get
